### ISSUE TITLE
What license is this project released with? 

### ISSUE THREAD

**Issue by williamwu0220** [noamelf/pycubator#17]
Hi, sir,

I would like to translate this slides to Chinese Traditional language, would this action is acceptable?

**Comment by oranja** [comment]
Hi William,
I am not an authority here, but I am watching this project and I can still
point you to the README. At the bottom you will find the CC-BY-SA tag.
In other words, the license is a Creative Commons license that allows you
to publish your own translation, as long as you link to the original (BY -
attrbution) and release your work under the same license (SA - share alike).

More details here: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by williamwu0220** [comment]
Sorry my bad, I missed the info in README, thanks. :)
